### ISSUE TITLE
Doesn't retry sending data after re-connecting to internet

### ISSUE THREAD

**Issue by trreed2** [kdesimini/ShuttleLogCollectionSystemSourceCode#1]
Issue: The issue is that after I submit the form when there is no internet, when i come back online it continues to retry to submit information and eventually fails to enter into database instead of pushing the data through and being done.

Product: Angular Front-End

Steps to reproduce: After page loads, i fill out the form on WiFi. Next i disconnect from WiFi and hit the add button on the form to try and submit data. Next i reconnect to WiFi. At that point it just keeps retrying to submit data until it fails.

In our live database at http://mildvariety.club/buslog/ There should be a new entry after the add button is pressed. After waiting a while, nothing shows up. 

My browser console output is:
<img width="810" alt="screen shot 2019-01-24 at 10 31 59 am" src="https://user-images.githubusercontent.com/34429274/51688784-4f3d1e00-1fc3-11e9-9a36-b321f2cef83c.png">

At "Attempt 3: retrying in 6000ms" I used the operating systems wifi button to reconnect the wifi. and the output continues to retry as shown above. 

I think it has to do with reference variables because the console output "Log {boarded: null, stop: null, loop: null, driver: "asd"}" says null when these values should have something.

**Comment by kdesimini** [comment]
Solved issue in person.
